version: '3.8'

services:
  dashboard:
    build: .
    container_name: inversion-dashboard
    restart: unless-stopped
    ports:
      - "8100:8000"
    volumes:
      # Montamos la carpeta IN desde el SSD
      - /Volumes/SSD-Datos/docker/apps/inv/IN:/app/IN
      # Montamos la carpeta raíz del SSD para que pueda leer y modificar Fondos.xlsx sin dar error de directorio
      #- /Volumes/SSD-Datos/docker/apps/inv/Fondos.xlsx:/app/Fondos.xlsx
      - /Volumes/SSD-Datos/docker/apps/inv/data:/app/data
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PORT=8000
